### ISSUE TITLE
param_feature should set `@tag feature: true`

### ISSUE THREAD

**Issue by s3cur3** [s3cur3/parameterized_test#22]
Without this, parameterized feature tests don't get excluded/included the same way `feature` tests do.

**Comment by zorn-allovue** [comment]
Enjoying my early tinkering with the library. Thanks for sharing.

I was attempting to do:

```elixir
    @tag skip: true
    param_test "scenario expectations", ...
```

And only observed a single test being skipped when I expected all of them in the group to be.

I think that is what this issue is meant to capture. Figured I'd comment/ask and subscribe.

**Comment by s3cur3** [comment]
Huh. I'm not sure what I was seeing when I created this, but the `feature` tag does indeed seem to be correctly applied. I can do both `mix test --only feature` and have it run my `param_feature` tests, and `mix test --exclude feature` to have it skip them.

@zorn-allovue, I opened another issue (#39) to address forwarding tags from the top-level `param_test`. 👍
