### ISSUE TITLE
Sometimes parameterized tests are skipped when running `mix test --failed`

### ISSUE THREAD

**Issue by axelson** [s3cur3/parameterized_test#31]
I looked into the cause of `mix test --failed` sometimes skipping some parameterized tests and I figured out that it's because parameterized_test generates test names like: `"test update_permission/4 updates billing for the team (%{new_permission: :view, initial_permission: :edit})"}`

And since maps don't have guaranteed ordering then when `mix test --failed` runs the test may instead be generated with a name like: `"test update_permission/4 updates billing for the team (%{initial_permission: :edit, new_permission: :view})"}` and will be mostly silently ignored (as a side-note it would be nice if `mix test --failed` was more strict about tests that no longer exist).

The fix is probably to not store the data as a map and instead store it as a keyword list so that we can preserve ordering information. It's a little hard to construct a repro for this because it depends on the ordering of a map which isn't stable.

**Comment by s3cur3** [comment]
Ohhh, interesting! Yeah, makes sense. Lemme see if I can fix that.

**Comment by s3cur3** [comment]
Released in [v0.5.0](https://github.com/s3cur3/parameterized_test/releases/tag/v0.5.0) 👍

**Comment by axelson** [comment]
Nice! Thank you!
